### ISSUE TITLE
MessagingController: Implement Authentication

### ISSUE THREAD

**Issue by joebiker** [Aldebaron/HW2#3]
## MessagingController

Implement the supplied function Authenticate function as the first step for each endpoint.
If it fails, `return NoContent();`

We'll implement the body of Authenticate at a later date. It's important to have a place for Authentication in each endpoint now.

### Notes
In this case, it will always succeed, however when debugging you can change the return type to test.

**Comment by Aldebaron** [comment]
So just adding "if (Authenticate(from) == false) { return NoContent(); }" to the three functions in Controller? I didn't add it to GetAll because there was no user parameter, and we'll take out GetAll once we're done testing it. Not sure what you mean by change the return type to test, though. The three functions didn't accept that, but they seemed happy with just returning NoContent() anyways.

**Comment by joebiker** [comment]
If you put a break point on line 101, you can manually change which way the authentication goes. Move the yellow arrow to the return statement you wish to test. Leave out the breakpoint for normal "good" behavior.

**Comment by joebiker** [comment]
Looks good. You can also shorten your if statement
if (!Authenticate(user))
The exclamation flips the boolean to the other.
