### ISSUE TITLE
Restructure Send 

### ISSUE THREAD

**Issue by joebiker** [Aldebaron/HW2#4]
Put the variables into the body of the HTTP request.
![image](https://user-images.githubusercontent.com/4908327/173887518-d84e62ed-ddd2-44e7-8e55-78db1e67ce0e.png)

**Comment by joebiker** [comment]
I pushed new code to change the functionality of send. 
I added comments talking about TODO items for @Aldebaron.

**Comment by Aldebaron** [comment]
I went through the TODO items and looked over the new changes, and left questions on the parts that I didn't understand.

**Comment by Aldebaron** [comment]
Sorry, didn't see that you pushed new comments until today. I went through your answers to my questions, and fixed the ordering bug.

**Comment by Aldebaron** [comment]
Went through and fixed the things you brought up in the service, plus messed around with SendMessage. Found a bug, and found a way around it but I don't think the solution works with what you had in mind.

**Comment by joebiker** [comment]
What is the bug? The caller should not be able to set the ID of the message. this is a system generated ID and must remain this way or a bad actor could create a duplicate unique id.  
Can you state the bug in more detail, perhaps give examples?

In the For loops, declare i in the for loop. for(int i=0...) Declaring i at the top of the function is not necessary (even if re-using i in another for loop).

**Comment by Aldebaron** [comment]
Sorry, the bug is just that it allows you to temporarily set a message ID. When the message gets to the Add() function, the ID gets overwritten, but in the process of sending the message you can mess with the ID, and the Accepted() message that gets returned contains the incorrect ID. For example, when sending a message, it allows you to input the ID as 300, and it returns an accepted message that lists the ID as 300. But if you check the database, that 300 was overwritten. So it's not a big bug, because it does get put into the database the right way. But it's kind of weird, I'm not sure what to do about it.

Fixed the declaration thing.
