### ISSUE TITLE
Logic Bomb

### ISSUE THREAD

**Issue by joebiker** [Aldebaron/HW2#5]
## Additionally, review this logic

if ((Messages[i].To == user || Messages[i].From == user) &&
   (Messages[i].To == other || Messages[i].From == other))

Compared to the inverse:
if ((Messages[i].To == user && Messages[i].From == user) ||
   (Messages[i].To == other && Messages[i].From == other))

### Questions
What are the differences between the two? 
Can you remove 'other' logic if you go with one or the other?

### More reading
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/boolean-logical-operators
Can you find other websites that discuss logical operators?

**Comment by Aldebaron** [comment]
The inverse evaluates to see if either the message was sent by the user to themselves, or by the other to themselves. Assuming that this is for reading messages sent between two individuals, I don't see how you could remove the "other" parameter unless you wanted to split this one loop into two, the first of which evaluating for the user's message and the second pulling out the other's messages from the list generated by the first. Otherwise, I have no idea.

I didn't realize there were so many more logical operators in C#! I might have already told you this, but I have a very strong background in Symbolic Logic. I was super excited to see the many-valued logic section in that article, I studied that a bit last semester, but I didn't consider the implications for coding!
