### ISSUE TITLE
Unit Testing and Pull Requests

### ISSUE THREAD

**Issue by joebiker** [Aldebaron/HW2#7]
## All Things Unit Tests

1) Review comments in UnitTest1.cs
1) Move all tests related to Messaging from UnitTest1.cs to MessagingTests.cs
1) Make changes to use the global variable MsgService. (everything should be in MessagingTests.cs now) 
1) Once all comments have been resolved, commit these changes.
1) When testing with a global class variable (MsgService). Each test will add messages to a common database. This could be good or bad. Why? You'll notice as you run tests, more messages get added to the database. How does this affect the count?
1) Next, remove the constructor and make a local messaging service variable (one for each [Fact]). Now you have specific control over what's added. How is this good or bad?
1) Commit these changes. In the commit message, including the issue number is really helpful. Additionally, write a SHORT summary of the goal of the commit.
1) Finally, create a PR -- Pull Request and select me as the reviewer, you as the assignee. I'll approve the request, then you'll complete the request. The goal here is to merge this unit test branch into the main line of development. This is typically how features are created then released into the main line of development. See also https://www.gitkraken.com/learn/git/git-flow

### Note: 
When adding messages or other "setup" for a test is considered as "Arrange". 
When you do the thing, you "Act". This would typically be running a function to do the work, for this example the best example is "reading" the messages from the database.
"Assert" is the part where you check the read messages to what you expect them to be.

**Comment by joebiker** [comment]
Still working on item 5 above: When testing with a global class variable (MsgService). Each test will add messages to a common database. This could be good or bad. Why? You'll notice as you run tests, more messages get added to the database. How does this affect the count?

**Comment by Aldebaron** [comment]
When using a global variable, the count varies. Now that the other tests use local variables (which is hopefully what I was supposed to do) CheckReadCountAlEJ passes, because the other tests are no longer contributing to the database with every run. Still, I don't fully understand how the global variable resulted in such a big variance that didn't even seem to correspond to anything that the other tests were doing. Using a global/common database is helpful when the tests are meant to be working together, but when they're more discrete functions, it can be a pain to keep track of how the previous tests affected the database in order to make predictions of expected values. Not only that, but for CheckReadCountAlEJ, I wasn't even able to make accurate predictions.

**Comment by joebiker** [comment]
I completed the pull request. This merged code into branch `main`. I then deleted the UnitTest branch. There should be only one now.  In your visual studio, switch back to `main` and pull the latest code. You should see comments from my last check in. 
Two things to complete: new end point, unit test clean up.
But first, create a new branch. Once you have that, you can "push" and you'll be able to see it on GitHub. Now get started on the next changes. Let me know if you have any questions.
